version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npassword
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myfirstappinn8n

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin  # Nome de usuário para autenticação
      - N8N_BASIC_AUTH_PASSWORD=changeme  # Altere a senha
    depends_on:
      - postgres
    networks:
      - myfirstappinn8n

  waha:
    image: devlikeapro/waha:latest
    ports:
      - "3000:3000"
    networks:
      - myfirstappinn8n

networks:
  myfirstappinn8n:
    driver: bridge

volumes:
  postgres_data:
